on:
    - workflow_dispatch
name: Deploy to prod
jobs:
    deploy_to_prod:
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: fake deploy
              run: sleep 5
            - name: Bump version and push tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v6.1
              with:
                github_token: ${{ secrets.GH_TOKEN }}
                default_bump: major