on:
    - push

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            REPO_NAME: ${{ steps.repo_namer.outputs.REPO_NAME }}
        steps:
            - name: make repo name lowercase
              id: repo_namer
              run: echo "REPO_NAME="$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"" > $GITHUB_OUTPUT
            
            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: build and run server
              run: docker build . -t tom && docker run -d -p 8000:8000 tom:latest

            - name: login to ghcr
              run: echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin

            - name: tag
              run: docker tag tom:latest ghcr.io/${{ steps.repo_namer.outputs.REPO_NAME }}:latest

            - name: push to ghcr
              run: docker push ghcr.io/${{ steps.repo_namer.outputs.REPO_NAME }}:latest
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
            - name: login to ghcr
              run: echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin

            - name: pull image
              run: docker pull ghcr.io/${{ needs.build.outputs.REPO_NAME }}:latest

            - name: run service
              run: docker run -d -p 8000:8000 ghcr.io/${{ needs.build.outputs.REPO_NAME }}:latest

            - name: install test requirements
              run: pip install -r test.requirements.txt
              
            - name: Run tests
              run: python test.py
    unit-tests:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v4.1.1
          - run: echo doing lots of tests
    deploy_to_stage:
        if: github.ref == 'refs/heads/main'
        needs: [test, unit-tests]
        runs-on: ubuntu-latest
        environment: stage
        steps:
            - name: Bump version and push tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v6.1
              with:
                github_token: ${{ secrets.GH_TOKEN }}
            - name: fake deploy
              run: sleep 5